/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Part = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'partNumber' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const Episode = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'description' : IDL.Text,
  'episodeNumber' : IDL.Nat,
  'parts' : IDL.Opt(IDL.Vec(Part)),
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const Season = IDL.Record({
  'title' : IDL.Text,
  'episodes' : IDL.Vec(Episode),
  'description' : IDL.Text,
  'seasonNumber' : IDL.Nat,
});
export const Category = IDL.Text;
export const ContentInput = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'seasons' : IDL.Opt(IDL.Vec(Season)),
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'posterUrl' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
});
export const ContentId = IDL.Text;
export const ContentItem = IDL.Record({
  'id' : ContentId,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'seasons' : IDL.Opt(IDL.Vec(Season)),
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'posterUrl' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addContent' : IDL.Func([ContentInput], [ContentId], []),
  'deleteContent' : IDL.Func([ContentId], [IDL.Bool], []),
  'getAllContent' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
  'getContentByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(ContentItem)],
      ['query'],
    ),
  'getContentById' : IDL.Func([ContentId], [IDL.Opt(ContentItem)], ['query']),
  'searchContent' : IDL.Func([IDL.Text], [IDL.Vec(ContentItem)], ['query']),
  'updateContent' : IDL.Func([ContentId, ContentInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Part = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'partNumber' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const Episode = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'description' : IDL.Text,
    'episodeNumber' : IDL.Nat,
    'parts' : IDL.Opt(IDL.Vec(Part)),
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const Season = IDL.Record({
    'title' : IDL.Text,
    'episodes' : IDL.Vec(Episode),
    'description' : IDL.Text,
    'seasonNumber' : IDL.Nat,
  });
  const Category = IDL.Text;
  const ContentInput = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'seasons' : IDL.Opt(IDL.Vec(Season)),
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'posterUrl' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
  });
  const ContentId = IDL.Text;
  const ContentItem = IDL.Record({
    'id' : ContentId,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'seasons' : IDL.Opt(IDL.Vec(Season)),
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'posterUrl' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
  });
  
  return IDL.Service({
    'addContent' : IDL.Func([ContentInput], [ContentId], []),
    'deleteContent' : IDL.Func([ContentId], [IDL.Bool], []),
    'getAllContent' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
    'getContentByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(ContentItem)],
        ['query'],
      ),
    'getContentById' : IDL.Func([ContentId], [IDL.Opt(ContentItem)], ['query']),
    'searchContent' : IDL.Func([IDL.Text], [IDL.Vec(ContentItem)], ['query']),
    'updateContent' : IDL.Func([ContentId, ContentInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };