/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export type ContentId = string;
export interface ContentInput {
  'title' : string,
  'duration' : string,
  'seasons' : [] | [Array<Season>],
  'year' : bigint,
  'description' : string,
  'genre' : string,
  'posterUrl' : string,
  'category' : Category,
  'rating' : number,
}
export interface ContentItem {
  'id' : ContentId,
  'title' : string,
  'duration' : string,
  'seasons' : [] | [Array<Season>],
  'year' : bigint,
  'description' : string,
  'genre' : string,
  'posterUrl' : string,
  'category' : Category,
  'rating' : number,
}
export interface Episode {
  'title' : string,
  'duration' : string,
  'description' : string,
  'episodeNumber' : bigint,
  'parts' : [] | [Array<Part>],
  'videoUrl' : [] | [string],
}
export interface Part {
  'title' : string,
  'duration' : string,
  'partNumber' : bigint,
  'videoUrl' : [] | [string],
}
export interface Season {
  'title' : string,
  'episodes' : Array<Episode>,
  'description' : string,
  'seasonNumber' : bigint,
}
export interface _SERVICE {
  'addContent' : ActorMethod<[ContentInput], ContentId>,
  'deleteContent' : ActorMethod<[ContentId], boolean>,
  'getAllContent' : ActorMethod<[], Array<ContentItem>>,
  'getContentByCategory' : ActorMethod<[Category], Array<ContentItem>>,
  'getContentById' : ActorMethod<[ContentId], [] | [ContentItem]>,
  'searchContent' : ActorMethod<[string], Array<ContentItem>>,
  'updateContent' : ActorMethod<[ContentId, ContentInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];