/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Part {
    title: string;
    duration: string;
    partNumber: bigint;
    videoUrl?: string;
}
export interface Season {
    title: string;
    episodes: Array<Episode>;
    description: string;
    seasonNumber: bigint;
}
export type ContentId = string;
export interface ContentItem {
    id: ContentId;
    title: string;
    duration: string;
    seasons?: Array<Season>;
    year: bigint;
    description: string;
    genre: string;
    posterUrl: string;
    category: Category;
    rating: number;
}
export interface ContentInput {
    title: string;
    duration: string;
    seasons?: Array<Season>;
    year: bigint;
    description: string;
    genre: string;
    posterUrl: string;
    category: Category;
    rating: number;
}
export type Category = string;
export interface Episode {
    title: string;
    duration: string;
    description: string;
    episodeNumber: bigint;
    parts?: Array<Part>;
    videoUrl?: string;
}
export interface backendInterface {
    addContent(input: ContentInput): Promise<ContentId>;
    deleteContent(id: ContentId): Promise<boolean>;
    getAllContent(): Promise<Array<ContentItem>>;
    getContentByCategory(category: Category): Promise<Array<ContentItem>>;
    getContentById(id: ContentId): Promise<ContentItem | null>;
    searchContent(term: string): Promise<Array<ContentItem>>;
    updateContent(id: ContentId, input: ContentInput): Promise<boolean>;
}
import type { Category as _Category, ContentId as _ContentId, ContentInput as _ContentInput, ContentItem as _ContentItem, Episode as _Episode, Part as _Part, Season as _Season } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContent(arg0: ContentInput): Promise<ContentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addContent(to_candid_ContentInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContent(to_candid_ContentInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteContent(arg0: ContentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContent(arg0);
            return result;
        }
    }
    async getAllContent(): Promise<Array<ContentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContent();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContent();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentByCategory(arg0: Category): Promise<Array<ContentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentByCategory(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentByCategory(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentById(arg0: ContentId): Promise<ContentItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentById(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentById(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchContent(arg0: string): Promise<Array<ContentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchContent(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchContent(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContent(arg0: ContentId, arg1: ContentInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContent(arg0, to_candid_ContentInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContent(arg0, to_candid_ContentInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ContentItem_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentItem): ContentItem {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Episode_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Episode): Episode {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Part_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Part): Part {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Season_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Season): Season {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Season>]): Array<Season> | null {
    return value.length === 0 ? null : from_candid_vec_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Part>]): Array<Part> | null {
    return value.length === 0 ? null : from_candid_vec_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContentItem]): ContentItem | null {
    return value.length === 0 ? null : from_candid_ContentItem_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ContentId;
    title: string;
    duration: string;
    seasons: [] | [Array<_Season>];
    year: bigint;
    description: string;
    genre: string;
    posterUrl: string;
    category: _Category;
    rating: number;
}): {
    id: ContentId;
    title: string;
    duration: string;
    seasons?: Array<Season>;
    year: bigint;
    description: string;
    genre: string;
    posterUrl: string;
    category: Category;
    rating: number;
} {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        seasons: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.seasons)),
        year: value.year,
        description: value.description,
        genre: value.genre,
        posterUrl: value.posterUrl,
        category: value.category,
        rating: value.rating
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    episodes: Array<_Episode>;
    description: string;
    seasonNumber: bigint;
}): {
    title: string;
    episodes: Array<Episode>;
    description: string;
    seasonNumber: bigint;
} {
    return {
        title: value.title,
        episodes: from_candid_vec_n19(_uploadFile, _downloadFile, value.episodes),
        description: value.description,
        seasonNumber: value.seasonNumber
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: string;
    description: string;
    episodeNumber: bigint;
    parts: [] | [Array<_Part>];
    videoUrl: [] | [string];
}): {
    title: string;
    duration: string;
    description: string;
    episodeNumber: bigint;
    parts?: Array<Part>;
    videoUrl?: string;
} {
    return {
        title: value.title,
        duration: value.duration,
        description: value.description,
        episodeNumber: value.episodeNumber,
        parts: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.parts)),
        videoUrl: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: string;
    partNumber: bigint;
    videoUrl: [] | [string];
}): {
    title: string;
    duration: string;
    partNumber: bigint;
    videoUrl?: string;
} {
    return {
        title: value.title,
        duration: value.duration,
        partNumber: value.partNumber,
        videoUrl: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentItem>): Array<ContentItem> {
    return value.map((x)=>from_candid_ContentItem_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Season>): Array<Season> {
    return value.map((x)=>from_candid_Season_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Episode>): Array<Episode> {
    return value.map((x)=>from_candid_Episode_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Part>): Array<Part> {
    return value.map((x)=>from_candid_Part_n24(_uploadFile, _downloadFile, x));
}
function to_candid_ContentInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentInput): _ContentInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Episode_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Episode): _Episode {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Part_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Part): _Part {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Season_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Season): _Season {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: string;
    partNumber: bigint;
    videoUrl?: string;
}): {
    title: string;
    duration: string;
    partNumber: bigint;
    videoUrl: [] | [string];
} {
    return {
        title: value.title,
        duration: value.duration,
        partNumber: value.partNumber,
        videoUrl: value.videoUrl ? candid_some(value.videoUrl) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: string;
    seasons?: Array<Season>;
    year: bigint;
    description: string;
    genre: string;
    posterUrl: string;
    category: Category;
    rating: number;
}): {
    title: string;
    duration: string;
    seasons: [] | [Array<_Season>];
    year: bigint;
    description: string;
    genre: string;
    posterUrl: string;
    category: _Category;
    rating: number;
} {
    return {
        title: value.title,
        duration: value.duration,
        seasons: value.seasons ? candid_some(to_candid_vec_n3(_uploadFile, _downloadFile, value.seasons)) : candid_none(),
        year: value.year,
        description: value.description,
        genre: value.genre,
        posterUrl: value.posterUrl,
        category: value.category,
        rating: value.rating
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    episodes: Array<Episode>;
    description: string;
    seasonNumber: bigint;
}): {
    title: string;
    episodes: Array<_Episode>;
    description: string;
    seasonNumber: bigint;
} {
    return {
        title: value.title,
        episodes: to_candid_vec_n6(_uploadFile, _downloadFile, value.episodes),
        description: value.description,
        seasonNumber: value.seasonNumber
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: string;
    description: string;
    episodeNumber: bigint;
    parts?: Array<Part>;
    videoUrl?: string;
}): {
    title: string;
    duration: string;
    description: string;
    episodeNumber: bigint;
    parts: [] | [Array<_Part>];
    videoUrl: [] | [string];
} {
    return {
        title: value.title,
        duration: value.duration,
        description: value.description,
        episodeNumber: value.episodeNumber,
        parts: value.parts ? candid_some(to_candid_vec_n9(_uploadFile, _downloadFile, value.parts)) : candid_none(),
        videoUrl: value.videoUrl ? candid_some(value.videoUrl) : candid_none()
    };
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Season>): Array<_Season> {
    return value.map((x)=>to_candid_Season_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Episode>): Array<_Episode> {
    return value.map((x)=>to_candid_Episode_n7(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Part>): Array<_Part> {
    return value.map((x)=>to_candid_Part_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
